version: "3.3"
services:
  handwai:
    image: handwai-python
    build:
      context: handwai-python/.
    ports:
      - 5000:5000
    restart: always
    volumes:
      - type: volume
        source: image_data_volume
        target: /app/images
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: mongod
  user-server:
    image: user-server
    build:
      context: handwai-user/.
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
  handwai-frontend:
    image: handwai-frontend
    build:
      context: handwai-frontend/.
    ports:
      - 8080:3000

    restart: always
    depends_on:
      - handwai
      - user-server
    links:
      - handwai
      - user-server
    volumes:
      - type: volume
        source: image_data_volume
        target: /app/src/images

volumes:
  mongodb_data_volume:
    external: true
  image_data_volume:
    external: true
